
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 22 15:56:35 CST 2018
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int slash = 39;
  public static final int zreadline = 47;
  public static final int admira = 28;
  public static final int aster = 40;
  public static final int zinterface = 5;
  public static final int zreturn = 12;
  public static final int coma = 26;
  public static final int igual = 33;
  public static final int llc = 21;
  public static final int zclass = 4;
  public static final int lla = 20;
  public static final int parac = 19;
  public static final int coc = 23;
  public static final int coa = 22;
  public static final int zreadinteger = 46;
  public static final int guin = 41;
  public static final int pipes = 29;
  public static final int dobleigual = 32;
  public static final int zbreak = 13;
  public static final int zgetbyte = 53;
  public static final int menor = 37;
  public static final int porcentaje = 38;
  public static final int EOF = 0;
  public static final int zsetbyte = 54;
  public static final int pyc = 27;
  public static final int zimplements = 43;
  public static final int mas = 42;
  public static final int andpers = 30;
  public static final int para = 18;
  public static final int error = 1;
  public static final int zif = 10;
  public static final int maigual = 34;
  public static final int mayor = 35;
  public static final int zinclude = 56;
  public static final int zmalloc = 48;
  public static final int negar = 31;
  public static final int zstring = 3;
  public static final int meigual = 36;
  public static final int zwhile = 9;
  public static final int punto = 25;
  public static final int zNewArray = 15;
  public static final int corcetes = 24;
  public static final int zbool = 52;
  public static final int id = 17;
  public static final int zthis = 7;
  public static final int zconst_string = 49;
  public static final int zconst_int = 57;
  public static final int zint = 51;
  public static final int zprint = 45;
  public static final int znull = 6;
  public static final int zNew = 14;
  public static final int zfor = 44;
  public static final int zextends = 8;
  public static final int zvoid = 2;
  public static final int zdouble = 16;
  public static final int zconstante_double = 50;
  public static final int cbool = 58;
  public static final int zconst = 55;
  public static final int zelse = 11;
}

