/* The following code was generated by JFlex 1.6.1 */

package compilador;
import static compilador.Token.*;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java_cup.runtime.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/compilador/reglas.flex</tt>
 */
class reglas implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  3, 66, 66,  1,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     2, 56, 21,  0,  0, 62, 58, 20, 48, 49, 64,  9, 54, 65, 46, 63, 
     5, 25, 25, 25, 25, 25, 25, 25,  4,  4,  0, 55, 61, 59, 60,  0, 
     0, 44,  7,  7,  7,  8, 47, 10, 10, 30, 10, 10, 32, 33, 43, 10, 
    26, 10, 28, 10, 10, 10, 10, 10,  6, 10, 10, 52, 22, 53,  0, 11, 
     0, 17, 23, 35, 29, 15, 16, 31, 37, 27, 10, 42, 18, 39, 24, 34, 
    40, 10, 13, 19, 12, 14, 36, 41, 38, 45, 10, 50, 57, 51,  0,  0, 
     0,  0,  0,  0,  0, 66,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\2\3\1\4\1\5\5\4\1\1"+
    "\12\4\1\6\1\4\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\2\1\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\3\1\27\1\0\6\4"+
    "\1\0\1\30\1\0\4\4\1\31\12\4\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\2\0\1\27\1\0\1\3\4\4\1\44\5\4\1\45"+
    "\7\4\1\46\1\4\4\0\1\27\1\0\1\3\1\47"+
    "\1\4\1\50\3\4\1\51\1\52\7\4\1\53\3\4"+
    "\2\54\1\0\1\43\1\0\1\27\3\4\1\55\1\56"+
    "\5\4\1\57\1\4\1\60\1\4\1\61\1\54\2\27"+
    "\1\62\1\4\1\30\4\4\1\63\2\4\1\64\11\4"+
    "\1\65\1\4\1\66\1\67\2\4\1\70\1\71\1\4"+
    "\1\72";

  private static int [] zzUnpackAction() {
    int [] result = new int[186];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\103\0\206\0\103\0\311\0\u010c\0\u014f\0\103"+
    "\0\u0192\0\u01d5\0\u0218\0\u025b\0\u029e\0\u02e1\0\u0324\0\u0367"+
    "\0\u03aa\0\u03ed\0\u0430\0\u0473\0\u04b6\0\u04f9\0\u053c\0\u057f"+
    "\0\103\0\u05c2\0\u0605\0\103\0\u0648\0\103\0\u068b\0\103"+
    "\0\103\0\103\0\u06ce\0\u0711\0\u0754\0\u0797\0\u07da\0\u081d"+
    "\0\103\0\u0860\0\103\0\103\0\u08a3\0\u08e6\0\u0929\0\u096c"+
    "\0\u09af\0\u09f2\0\u0a35\0\u0a78\0\u0abb\0\u02e1\0\103\0\u0afe"+
    "\0\u0b41\0\u0b84\0\u0bc7\0\u0c0a\0\u014f\0\u0c4d\0\u0c90\0\u0cd3"+
    "\0\u0d16\0\u0d59\0\u0d9c\0\u0ddf\0\u0e22\0\u0e65\0\u0ea8\0\103"+
    "\0\103\0\103\0\103\0\103\0\103\0\103\0\103\0\103"+
    "\0\u0eeb\0\u0f2e\0\u0f71\0\u0fb4\0\u0ff7\0\u103a\0\u107d\0\u10c0"+
    "\0\u1103\0\u1146\0\u014f\0\u1189\0\u11cc\0\u120f\0\u1252\0\u1295"+
    "\0\u12d8\0\u131b\0\u135e\0\u13a1\0\u13e4\0\u1427\0\u146a\0\u14ad"+
    "\0\u14f0\0\u1533\0\u1576\0\u15b9\0\u15fc\0\u163f\0\u1682\0\u1682"+
    "\0\u16c5\0\u014f\0\u1708\0\u014f\0\u174b\0\u178e\0\u17d1\0\u014f"+
    "\0\u014f\0\u1814\0\u1857\0\u189a\0\u18dd\0\u1920\0\u1963\0\u19a6"+
    "\0\u014f\0\u19e9\0\u1a2c\0\u1a6f\0\u1576\0\u1ab2\0\u1af5\0\103"+
    "\0\u1b38\0\u1b7b\0\u1bbe\0\u1c01\0\u1c44\0\u014f\0\u014f\0\u1c87"+
    "\0\u1cca\0\u1d0d\0\u1d50\0\u1d93\0\u014f\0\u1dd6\0\u014f\0\u1e19"+
    "\0\u014f\0\u1e5c\0\u1e9f\0\u1ee2\0\u014f\0\u1f25\0\u014f\0\u1f68"+
    "\0\u1fab\0\u1fee\0\u2031\0\u014f\0\u2074\0\u20b7\0\u014f\0\u20fa"+
    "\0\u213d\0\u2180\0\u21c3\0\u2206\0\u2249\0\u228c\0\u22cf\0\u2312"+
    "\0\u014f\0\u2355\0\u014f\0\u014f\0\u2398\0\u23db\0\u014f\0\u014f"+
    "\0\u241e\0\u014f";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[186];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\6\3\7\1\10\1\7"+
    "\1\2\1\11\1\12\1\7\1\13\1\14\2\7\1\15"+
    "\1\2\1\16\1\2\1\17\1\20\1\5\1\21\1\22"+
    "\1\23\4\7\1\24\1\7\1\25\1\26\4\7\1\27"+
    "\1\7\1\30\2\7\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\1\53\1\54\107\0"+
    "\1\4\103\0\1\5\1\55\23\0\1\5\24\0\1\56"+
    "\30\0\1\5\1\55\1\57\22\0\1\5\14\0\1\57"+
    "\7\0\1\56\30\0\5\7\1\0\12\7\3\0\27\7"+
    "\1\0\1\7\27\0\5\7\1\0\12\7\3\0\16\7"+
    "\1\60\10\7\1\0\1\7\27\0\5\7\1\0\5\7"+
    "\1\61\4\7\3\0\27\7\1\0\1\7\27\0\5\7"+
    "\1\0\10\7\1\62\1\7\3\0\17\7\1\63\7\7"+
    "\1\0\1\7\27\0\5\7\1\0\12\7\3\0\13\7"+
    "\1\64\13\7\1\0\1\7\27\0\5\7\1\0\2\7"+
    "\1\65\7\7\3\0\27\7\1\0\1\7\23\0\1\66"+
    "\1\0\1\66\1\0\21\66\1\67\1\70\54\66\4\0"+
    "\5\7\1\0\3\7\1\71\6\7\3\0\13\7\1\72"+
    "\13\7\1\0\1\7\27\0\5\7\1\0\4\7\1\73"+
    "\5\7\3\0\27\7\1\0\1\7\27\0\5\7\1\0"+
    "\3\7\1\74\6\7\3\0\27\7\1\0\1\7\27\0"+
    "\5\7\1\0\6\7\1\75\3\7\3\0\1\7\1\76"+
    "\16\7\1\77\6\7\1\0\1\7\27\0\5\7\1\0"+
    "\5\7\1\100\4\7\3\0\27\7\1\0\1\7\27\0"+
    "\5\7\1\0\7\7\1\101\2\7\3\0\27\7\1\0"+
    "\1\7\27\0\5\7\1\0\10\7\1\102\1\7\3\0"+
    "\13\7\1\103\13\7\1\0\1\7\27\0\5\7\1\0"+
    "\12\7\3\0\13\7\1\104\13\7\1\0\1\7\27\0"+
    "\5\7\1\0\12\7\3\0\16\7\1\105\10\7\1\0"+
    "\1\7\27\0\5\7\1\0\5\7\1\106\4\7\3\0"+
    "\27\7\1\0\1\7\27\0\5\7\1\0\10\7\1\107"+
    "\1\7\3\0\27\7\1\0\1\7\104\0\1\110\104\0"+
    "\1\111\104\0\1\112\110\0\1\113\100\0\1\114\103\0"+
    "\1\115\103\0\1\116\102\0\1\117\102\0\1\120\106\0"+
    "\1\121\1\122\6\0\1\5\1\55\1\123\22\0\1\5"+
    "\14\0\1\123\7\0\1\56\30\0\1\56\1\124\2\0"+
    "\1\125\6\0\1\125\11\0\1\56\55\0\2\126\1\0"+
    "\2\126\6\0\3\126\5\0\1\126\1\0\1\126\3\0"+
    "\1\126\5\0\1\126\10\0\1\126\2\0\1\126\27\0"+
    "\5\7\1\0\12\7\3\0\4\7\1\127\22\7\1\0"+
    "\1\7\27\0\5\7\1\0\2\7\1\130\7\7\3\0"+
    "\27\7\1\0\1\7\27\0\5\7\1\0\11\7\1\131"+
    "\3\0\27\7\1\0\1\7\27\0\5\7\1\0\2\7"+
    "\1\132\7\7\3\0\27\7\1\0\1\7\27\0\5\7"+
    "\1\0\3\7\1\133\6\7\3\0\27\7\1\0\1\7"+
    "\27\0\5\7\1\0\3\7\1\134\6\7\3\0\27\7"+
    "\1\0\1\7\30\0\1\66\6\0\2\66\2\0\1\66"+
    "\3\0\6\66\55\0\5\7\1\0\5\7\1\135\4\7"+
    "\3\0\27\7\1\0\1\7\27\0\5\7\1\0\12\7"+
    "\3\0\13\7\1\136\13\7\1\0\1\7\27\0\5\7"+
    "\1\0\10\7\1\137\1\7\3\0\27\7\1\0\1\7"+
    "\27\0\5\7\1\0\12\7\3\0\4\7\1\140\22\7"+
    "\1\0\1\7\27\0\5\7\1\0\2\7\1\141\7\7"+
    "\3\0\27\7\1\0\1\7\27\0\5\7\1\0\12\7"+
    "\3\0\21\7\1\142\5\7\1\0\1\7\27\0\5\7"+
    "\1\0\7\7\1\143\2\7\3\0\27\7\1\0\1\7"+
    "\27\0\5\7\1\0\10\7\1\144\1\7\3\0\27\7"+
    "\1\0\1\7\27\0\5\7\1\0\7\7\1\145\2\7"+
    "\3\0\27\7\1\0\1\7\27\0\5\7\1\0\12\7"+
    "\3\0\1\7\1\146\25\7\1\0\1\7\27\0\5\7"+
    "\1\0\12\7\3\0\4\7\1\147\22\7\1\0\1\7"+
    "\27\0\5\7\1\0\12\7\3\0\4\7\1\150\22\7"+
    "\1\0\1\7\27\0\5\7\1\0\12\7\3\0\22\7"+
    "\1\151\4\7\1\0\1\7\27\0\5\7\1\0\12\7"+
    "\3\0\13\7\1\152\13\7\1\0\1\7\23\0\1\121"+
    "\1\0\1\121\1\0\77\121\100\153\1\154\2\153\4\0"+
    "\2\155\1\0\2\155\6\0\3\155\5\0\1\155\1\0"+
    "\1\155\3\0\1\155\5\0\1\155\10\0\1\155\2\0"+
    "\1\155\27\0\1\56\1\124\1\156\1\0\1\125\6\0"+
    "\1\125\11\0\1\56\14\0\1\156\40\0\2\157\3\0"+
    "\1\160\17\0\1\157\47\0\1\160\5\0\1\126\1\161"+
    "\1\0\2\126\6\0\3\126\5\0\1\126\1\0\1\126"+
    "\3\0\1\126\5\0\1\126\10\0\1\126\1\0\1\56"+
    "\1\126\27\0\5\7\1\0\11\7\1\162\3\0\27\7"+
    "\1\0\1\7\27\0\5\7\1\0\4\7\1\163\5\7"+
    "\3\0\27\7\1\0\1\7\27\0\5\7\1\0\5\7"+
    "\1\164\4\7\3\0\27\7\1\0\1\7\27\0\5\7"+
    "\1\0\5\7\1\165\4\7\3\0\27\7\1\0\1\7"+
    "\27\0\5\7\1\0\12\7\3\0\4\7\1\166\22\7"+
    "\1\0\1\7\27\0\5\7\1\0\7\7\1\167\2\7"+
    "\3\0\27\7\1\0\1\7\27\0\5\7\1\0\10\7"+
    "\1\170\1\7\3\0\27\7\1\0\1\7\27\0\5\7"+
    "\1\0\10\7\1\171\1\7\3\0\27\7\1\0\1\7"+
    "\27\0\5\7\1\0\12\7\3\0\1\7\1\172\25\7"+
    "\1\0\1\7\27\0\5\7\1\0\5\7\1\173\4\7"+
    "\3\0\27\7\1\0\1\7\27\0\5\7\1\0\10\7"+
    "\1\174\1\7\3\0\27\7\1\0\1\7\27\0\5\7"+
    "\1\0\12\7\3\0\6\7\1\175\20\7\1\0\1\7"+
    "\27\0\5\7\1\0\10\7\1\176\1\7\3\0\27\7"+
    "\1\0\1\7\27\0\5\7\1\0\11\7\1\177\3\0"+
    "\27\7\1\0\1\7\27\0\5\7\1\0\11\7\1\200"+
    "\3\0\27\7\1\0\1\7\27\0\5\7\1\0\12\7"+
    "\3\0\6\7\1\201\20\7\1\0\1\7\27\0\5\7"+
    "\1\0\10\7\1\202\1\7\3\0\27\7\1\0\1\7"+
    "\27\0\5\7\1\0\12\7\3\0\25\7\1\203\1\7"+
    "\1\0\1\7\27\0\5\7\1\0\7\7\1\204\2\7"+
    "\3\0\27\7\1\0\1\7\23\0\77\205\1\153\1\206"+
    "\2\205\77\207\1\210\1\154\2\207\4\0\1\155\1\211"+
    "\1\0\2\155\6\0\3\155\5\0\1\155\1\0\1\155"+
    "\3\0\1\155\5\0\1\155\10\0\1\155\1\0\1\56"+
    "\1\155\27\0\2\212\1\0\2\212\6\0\3\212\5\0"+
    "\1\212\1\0\1\212\3\0\1\212\5\0\1\212\10\0"+
    "\1\212\2\0\1\212\27\0\2\157\23\0\1\157\55\0"+
    "\1\126\1\161\1\123\2\126\6\0\3\126\5\0\1\126"+
    "\1\0\1\126\3\0\1\126\5\0\1\126\2\0\1\123"+
    "\5\0\1\126\1\0\1\56\1\126\27\0\5\7\1\0"+
    "\3\7\1\213\6\7\3\0\27\7\1\0\1\7\27\0"+
    "\5\7\1\0\12\7\3\0\1\7\1\214\25\7\1\0"+
    "\1\7\27\0\5\7\1\0\12\7\3\0\1\7\1\215"+
    "\25\7\1\0\1\7\27\0\5\7\1\0\12\7\3\0"+
    "\23\7\1\216\3\7\1\0\1\7\27\0\5\7\1\0"+
    "\2\7\1\217\7\7\3\0\27\7\1\0\1\7\27\0"+
    "\5\7\1\0\3\7\1\220\6\7\3\0\27\7\1\0"+
    "\1\7\27\0\5\7\1\0\5\7\1\221\4\7\3\0"+
    "\27\7\1\0\1\7\27\0\5\7\1\0\12\7\3\0"+
    "\7\7\1\222\1\7\1\223\15\7\1\0\1\7\27\0"+
    "\5\7\1\0\12\7\3\0\13\7\1\224\13\7\1\0"+
    "\1\7\27\0\5\7\1\0\11\7\1\225\3\0\27\7"+
    "\1\0\1\7\27\0\5\7\1\0\2\7\1\226\7\7"+
    "\3\0\27\7\1\0\1\7\27\0\5\7\1\0\5\7"+
    "\1\227\4\7\3\0\27\7\1\0\1\7\27\0\5\7"+
    "\1\0\3\7\1\230\6\7\3\0\27\7\1\0\1\7"+
    "\27\0\5\7\1\0\2\7\1\231\7\7\3\0\27\7"+
    "\1\0\1\7\23\0\77\232\1\210\1\206\2\232\100\207"+
    "\1\154\2\207\4\0\1\155\1\211\1\123\2\155\6\0"+
    "\3\155\5\0\1\155\1\0\1\155\3\0\1\155\5\0"+
    "\1\155\2\0\1\123\5\0\1\155\1\0\1\56\1\155"+
    "\27\0\1\212\1\233\1\0\1\212\1\234\6\0\1\234"+
    "\2\212\5\0\1\212\1\0\1\212\3\0\1\212\5\0"+
    "\1\212\10\0\1\212\2\0\1\212\27\0\5\7\1\0"+
    "\12\7\3\0\1\7\1\235\25\7\1\0\1\7\27\0"+
    "\5\7\1\0\12\7\3\0\6\7\1\236\20\7\1\0"+
    "\1\7\27\0\5\7\1\0\12\7\3\0\10\7\1\237"+
    "\16\7\1\0\1\7\27\0\5\7\1\0\6\7\1\240"+
    "\3\7\3\0\27\7\1\0\1\7\27\0\5\7\1\0"+
    "\12\7\3\0\20\7\1\241\6\7\1\0\1\7\27\0"+
    "\5\7\1\0\12\7\3\0\1\7\1\242\25\7\1\0"+
    "\1\7\27\0\5\7\1\0\12\7\3\0\4\7\1\243"+
    "\22\7\1\0\1\7\27\0\5\7\1\0\12\7\3\0"+
    "\14\7\1\244\12\7\1\0\1\7\27\0\5\7\1\0"+
    "\7\7\1\245\2\7\3\0\27\7\1\0\1\7\27\0"+
    "\5\7\1\0\3\7\1\246\6\7\3\0\27\7\1\0"+
    "\1\7\23\0\77\232\1\207\1\206\2\232\4\0\1\212"+
    "\1\233\1\156\1\212\1\234\6\0\1\234\2\212\5\0"+
    "\1\212\1\0\1\212\3\0\1\212\5\0\1\212\2\0"+
    "\1\156\5\0\1\212\2\0\1\212\27\0\1\212\1\233"+
    "\1\0\1\212\1\234\1\160\5\0\1\234\2\212\5\0"+
    "\1\212\1\0\1\212\3\0\1\212\5\0\1\212\10\0"+
    "\1\212\2\0\1\212\21\0\1\160\5\0\5\7\1\0"+
    "\11\7\1\247\3\0\27\7\1\0\1\7\27\0\5\7"+
    "\1\0\7\7\1\250\2\7\3\0\27\7\1\0\1\7"+
    "\27\0\5\7\1\0\5\7\1\251\4\7\3\0\27\7"+
    "\1\0\1\7\27\0\5\7\1\0\2\7\1\252\7\7"+
    "\3\0\27\7\1\0\1\7\27\0\5\7\1\0\12\7"+
    "\3\0\1\7\1\253\25\7\1\0\1\7\27\0\5\7"+
    "\1\0\12\7\3\0\1\7\1\254\25\7\1\0\1\7"+
    "\27\0\5\7\1\0\7\7\1\255\2\7\3\0\27\7"+
    "\1\0\1\7\27\0\5\7\1\0\12\7\3\0\14\7"+
    "\1\256\12\7\1\0\1\7\27\0\5\7\1\0\12\7"+
    "\3\0\1\7\1\257\25\7\1\0\1\7\27\0\5\7"+
    "\1\0\5\7\1\260\4\7\3\0\27\7\1\0\1\7"+
    "\27\0\5\7\1\0\5\7\1\261\4\7\3\0\27\7"+
    "\1\0\1\7\27\0\5\7\1\0\2\7\1\262\7\7"+
    "\3\0\27\7\1\0\1\7\27\0\5\7\1\0\12\7"+
    "\3\0\26\7\1\263\1\0\1\7\27\0\5\7\1\0"+
    "\5\7\1\264\4\7\3\0\27\7\1\0\1\7\27\0"+
    "\5\7\1\0\2\7\1\265\7\7\3\0\27\7\1\0"+
    "\1\7\27\0\5\7\1\0\12\7\3\0\10\7\1\266"+
    "\16\7\1\0\1\7\27\0\5\7\1\0\5\7\1\267"+
    "\4\7\3\0\27\7\1\0\1\7\27\0\5\7\1\0"+
    "\11\7\1\270\3\0\27\7\1\0\1\7\27\0\5\7"+
    "\1\0\5\7\1\271\4\7\3\0\27\7\1\0\1\7"+
    "\27\0\5\7\1\0\3\7\1\272\6\7\3\0\27\7"+
    "\1\0\1\7\23\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[9313];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\3\1\1\11\20\1\1\11"+
    "\2\1\1\11\1\1\1\11\1\1\3\11\6\1\1\11"+
    "\1\1\2\11\2\1\1\0\6\1\1\0\1\11\1\0"+
    "\17\1\11\11\1\1\2\0\1\1\1\0\25\1\4\0"+
    "\1\1\1\0\26\1\1\0\1\11\1\0\61\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[186];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */

public String posiciocn(String token){

       String auxiliar = yytext();
int col = auxiliar.length();
boolean truncado = false;
         if (token.compareTo("Id")==0) {
        if (col>31) {
            auxiliar = auxiliar.substring(0, 31);
truncado = true;
        }
    }
col += yycolumn;
if(truncado){
//return "Token: "+ token +" -> " +"<" + auxiliar + "> " +" ***Id truncado*** "+ "Línea: " + yyline + " Columna: " + yycolumn +"-"+col;
return token+","+auxiliar+"*"+","+yyline+","+yycolumn +"-"+col;
}
else{
//return "Token: "+ token +" -> " +"<" + auxiliar + "> " + "Línea: " + yyline + " Columna: " + yycolumn +"-"+col;
return token+","+auxiliar+","+yyline+","+yycolumn +"-"+col;
}
      

}



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  reglas(java.io.Reader in) {
      this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("error lexico"); return new Symbol(sym.error,yyline,yycolumn,yytext()););
            }
          case 59: break;
          case 2: 
            { 
            }
          case 60: break;
          case 3: 
            { System.out.println(yytext()); return new Symbol(sym.zint,yyline,yycolumn,yytext());
            }
          case 61: break;
          case 4: 
            { return new Symbol(sym.id);
            }
          case 62: break;
          case 5: 
            { System.out.println("mas"); return new Symbol(sym.mas,yyline,yycolumn,yytext());
            }
          case 63: break;
          case 6: 
            { return new Symbol(sym.punto);
            }
          case 64: break;
          case 7: 
            { return new Symbol(sym.para,yyline,yycolumn,yytext());
            }
          case 65: break;
          case 8: 
            { return new Symbol(sym.parac,yyline,yycolumn,yytext());
            }
          case 66: break;
          case 9: 
            { return new Symbol(sym.lla);
            }
          case 67: break;
          case 10: 
            { return new Symbol(sym.llc);
            }
          case 68: break;
          case 11: 
            { return new Symbol(sym.coa);
            }
          case 69: break;
          case 12: 
            { return new Symbol(sym.coc);
            }
          case 70: break;
          case 13: 
            { return new Symbol(sym.coma);
            }
          case 71: break;
          case 14: 
            { return new Symbol(sym.pyc);
            }
          case 72: break;
          case 15: 
            { return new Symbol(sym.admira);
            }
          case 73: break;
          case 16: 
            { return new Symbol(sym.igual);
            }
          case 74: break;
          case 17: 
            { return new Symbol(sym.mayor);
            }
          case 75: break;
          case 18: 
            { return new Symbol(sym.menor);
            }
          case 76: break;
          case 19: 
            { return new Symbol(sym.porcentaje);
            }
          case 77: break;
          case 20: 
            { System.out.println("dividido"); return new Symbol(sym.slash,yyline,yycolumn,yytext());
            }
          case 78: break;
          case 21: 
            { System.out.println("por"); return new Symbol(sym.aster,yyline,yycolumn,yytext());
            }
          case 79: break;
          case 22: 
            { System.out.println("menos"); return new Symbol(sym.guin,yyline,yycolumn,yytext());
            }
          case 80: break;
          case 23: 
            { return new Symbol(sym.zdouble);
            }
          case 81: break;
          case 24: 
            { return new Symbol(sym.zstring);
            }
          case 82: break;
          case 25: 
            { return new Symbol(sym.zif);
            }
          case 83: break;
          case 26: 
            { return new Symbol(sym.paren);
            }
          case 84: break;
          case 27: 
            { return new Symbol(sym.llaves);
            }
          case 85: break;
          case 28: 
            { return new Symbol(sym.corcetes);
            }
          case 86: break;
          case 29: 
            { return new Symbol(sym.negar);
            }
          case 87: break;
          case 30: 
            { return new Symbol(sym.pipes);
            }
          case 88: break;
          case 31: 
            { return new Symbol(sym.andpers);
            }
          case 89: break;
          case 32: 
            { return new Symbol(sym.dobleigual);
            }
          case 90: break;
          case 33: 
            { return new Symbol(sym.maigual);
            }
          case 91: break;
          case 34: 
            { return new Symbol(sym.meigual);
            }
          case 92: break;
          case 35: 
            { System.out.println("Comentario");
            }
          case 93: break;
          case 36: 
            { return new Symbol(sym.zfor);
            }
          case 94: break;
          case 37: 
            { return new Symbol(sym.zint);
            }
          case 95: break;
          case 38: 
            { return new Symbol(sym.zNew);
            }
          case 96: break;
          case 39: 
            { return new Symbol(sym.zthis);
            }
          case 97: break;
          case 40: 
            { return new Symbol(sym.zelse);
            }
          case 98: break;
          case 41: 
            { return new Symbol(sym.zbool);
            }
          case 99: break;
          case 42: 
            { return new Symbol(sym.znull);
            }
          case 100: break;
          case 43: 
            { return new Symbol(sym.zvoid);
            }
          case 101: break;
          case 44: 
            { return new Symbol(sym.error,yyline,yycolumn,yytext()););
            }
          case 102: break;
          case 45: 
            { return new Symbol(sym.zbreak);
            }
          case 103: break;
          case 46: 
            { return new Symbol(sym.zprint);
            }
          case 104: break;
          case 47: 
            { return new Symbol(sym.zclass);
            }
          case 105: break;
          case 48: 
            { return new Symbol(sym.zwhile);
            }
          case 106: break;
          case 49: 
            { return new Symbol(sym.zFloat);
            }
          case 107: break;
          case 50: 
            { return new Symbol(sym.zreturn);
            }
          case 108: break;
          case 51: 
            { return new Symbol(sym.zmalloc);
            }
          case 109: break;
          case 52: 
            { return new Symbol(sym.zextends);
            }
          case 110: break;
          case 53: 
            { return new Symbol(sym.zreadline);
            }
          case 111: break;
          case 54: 
            { return new Symbol(sym.zNewArray);
            }
          case 112: break;
          case 55: 
            { return new Symbol(sym.zinterface);
            }
          case 113: break;
          case 56: 
            { return new Symbol(sym.zConstante);
            }
          case 114: break;
          case 57: 
            { return new Symbol(sym.zimplements);
            }
          case 115: break;
          case 58: 
            { return new Symbol(sym.zreadinteger);
            }
          case 116: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
