/* The following code was generated by JFlex 1.6.1 */

package compilador;
import static compilador.Token.*;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>C:/Users/Mario/Documents/NetBeansProjects/compilador/src/compilador/reglas.flex</tt>
 */
class reglas {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\2\1\3\1\74\1\74\1\1\22\0\1\2\1\62\1\25"+
    "\2\0\1\70\1\64\1\24\1\52\1\53\1\72\1\11\1\60\1\73"+
    "\1\10\1\71\1\4\3\31\4\31\2\5\1\0\1\61\1\67\1\65"+
    "\1\66\2\0\1\47\3\7\1\7\1\51\7\12\1\46\11\12\1\6"+
    "\2\12\1\56\1\26\1\57\1\0\1\13\1\0\1\21\1\27\1\37"+
    "\1\35\1\17\1\20\1\36\1\40\1\34\1\12\1\45\1\22\1\42"+
    "\1\30\1\33\1\43\1\12\1\15\1\23\1\14\1\16\1\32\1\44"+
    "\1\41\1\50\1\12\1\54\1\63\1\55\7\0\1\74\u1fa2\0\1\74"+
    "\1\74\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\2\3\1\4\1\5\1\6\5\4"+
    "\1\1\11\4\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\2\1\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\0\6\4\1\0\1\27\1\0"+
    "\4\4\1\30\10\4\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\0\1\3\4\4"+
    "\1\43\5\4\1\44\5\4\1\45\1\4\1\0\1\46"+
    "\1\4\1\47\3\4\1\50\1\51\1\52\10\4\1\53"+
    "\3\4\1\54\3\4\1\55\1\4\1\56\1\4\1\57"+
    "\1\60\1\4\1\61\2\4\1\62\2\4\1\63\7\4"+
    "\1\64\1\65\1\4\1\66\1\67";

  private static int [] zzUnpackAction() {
    int [] result = new int[147];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\75\0\172\0\75\0\267\0\364\0\u0131\0\75"+
    "\0\75\0\u016e\0\u01ab\0\u01e8\0\u0225\0\u0262\0\u029f\0\u02dc"+
    "\0\u0319\0\u0356\0\u0393\0\u03d0\0\u040d\0\u044a\0\u0487\0\u04c4"+
    "\0\u0501\0\75\0\u053e\0\75\0\u057b\0\75\0\75\0\75"+
    "\0\u05b8\0\u05f5\0\u0632\0\u066f\0\u06ac\0\u06e9\0\75\0\u0726"+
    "\0\75\0\75\0\u0763\0\u07a0\0\u07dd\0\u081a\0\u0857\0\u0894"+
    "\0\u08d1\0\u029f\0\75\0\u090e\0\u094b\0\u0988\0\u09c5\0\u0a02"+
    "\0\u0131\0\u0a3f\0\u0a7c\0\u0ab9\0\u0af6\0\u0b33\0\u0b70\0\u0bad"+
    "\0\u0bea\0\75\0\75\0\75\0\75\0\75\0\75\0\75"+
    "\0\75\0\75\0\u0c27\0\u0c64\0\u0763\0\u0ca1\0\u0cde\0\u0d1b"+
    "\0\u0d58\0\u0131\0\u0d95\0\u0dd2\0\u0e0f\0\u0e4c\0\u0e89\0\u0ec6"+
    "\0\u0f03\0\u0f40\0\u0f7d\0\u0fba\0\u0ff7\0\u1034\0\u1071\0\u10ae"+
    "\0\u0131\0\u10eb\0\u0131\0\u1128\0\u1165\0\u11a2\0\u0131\0\u0131"+
    "\0\u0131\0\u11df\0\u121c\0\u1259\0\u1296\0\u12d3\0\u1310\0\u134d"+
    "\0\u138a\0\75\0\u13c7\0\u1404\0\u1441\0\u0131\0\u147e\0\u14bb"+
    "\0\u14f8\0\u0131\0\u1535\0\u0131\0\u1572\0\u0131\0\u0131\0\u15af"+
    "\0\u0131\0\u15ec\0\u1629\0\u0131\0\u1666\0\u16a3\0\u0131\0\u16e0"+
    "\0\u171d\0\u175a\0\u1797\0\u17d4\0\u1811\0\u184e\0\u0131\0\u0131"+
    "\0\u188b\0\u0131\0\u0131";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[147];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\6\2\7\1\10\1\11"+
    "\1\7\1\2\1\12\1\13\1\7\1\14\1\15\2\7"+
    "\1\16\1\2\1\17\1\2\1\20\1\21\1\6\1\22"+
    "\1\7\1\23\1\24\1\7\1\25\4\7\1\26\1\7"+
    "\1\27\2\7\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\101\0\1\4\77\0"+
    "\1\53\32\0\1\53\37\0\2\6\23\0\1\6\47\0"+
    "\4\7\2\0\12\7\3\0\23\7\27\0\4\7\2\0"+
    "\12\7\3\0\11\7\1\54\11\7\27\0\4\7\2\0"+
    "\5\7\1\55\4\7\3\0\23\7\27\0\4\7\2\0"+
    "\10\7\1\56\1\7\3\0\12\7\1\57\10\7\27\0"+
    "\4\7\2\0\12\7\3\0\4\7\1\60\16\7\27\0"+
    "\4\7\2\0\2\7\1\61\7\7\3\0\23\7\23\0"+
    "\1\62\1\0\1\62\1\0\21\62\1\63\1\64\46\62"+
    "\4\0\4\7\2\0\3\7\1\65\6\7\3\0\4\7"+
    "\1\66\16\7\27\0\4\7\2\0\4\7\1\67\5\7"+
    "\3\0\23\7\27\0\4\7\2\0\12\7\3\0\4\7"+
    "\1\70\16\7\27\0\4\7\2\0\6\7\1\71\3\7"+
    "\3\0\1\7\1\72\11\7\1\73\7\7\27\0\4\7"+
    "\2\0\12\7\3\0\4\7\1\74\16\7\27\0\4\7"+
    "\2\0\10\7\1\75\1\7\3\0\4\7\1\76\16\7"+
    "\27\0\4\7\2\0\12\7\3\0\11\7\1\77\11\7"+
    "\27\0\4\7\2\0\5\7\1\100\4\7\3\0\23\7"+
    "\27\0\4\7\2\0\10\7\1\101\1\7\3\0\23\7"+
    "\76\0\1\102\76\0\1\103\76\0\1\104\102\0\1\105"+
    "\72\0\1\106\75\0\1\107\75\0\1\110\74\0\1\111"+
    "\74\0\1\112\100\0\1\113\1\114\6\0\2\115\1\0"+
    "\1\115\7\0\3\115\5\0\1\115\1\0\1\115\3\0"+
    "\1\115\1\0\1\115\7\0\1\115\1\0\1\115\27\0"+
    "\4\7\2\0\12\7\3\0\5\7\1\116\15\7\27\0"+
    "\4\7\2\0\2\7\1\117\7\7\3\0\23\7\27\0"+
    "\4\7\2\0\11\7\1\120\3\0\23\7\27\0\4\7"+
    "\2\0\2\7\1\121\7\7\3\0\23\7\27\0\4\7"+
    "\2\0\3\7\1\122\6\7\3\0\23\7\27\0\4\7"+
    "\2\0\3\7\1\123\6\7\3\0\23\7\27\0\1\62"+
    "\7\0\2\62\2\0\1\62\3\0\6\62\47\0\4\7"+
    "\2\0\5\7\1\124\4\7\3\0\23\7\27\0\4\7"+
    "\2\0\12\7\3\0\4\7\1\125\16\7\27\0\4\7"+
    "\2\0\10\7\1\126\1\7\3\0\23\7\27\0\4\7"+
    "\2\0\12\7\3\0\5\7\1\127\15\7\27\0\4\7"+
    "\2\0\2\7\1\130\7\7\3\0\23\7\27\0\4\7"+
    "\2\0\12\7\3\0\14\7\1\131\6\7\27\0\4\7"+
    "\2\0\4\7\1\132\5\7\3\0\23\7\27\0\4\7"+
    "\2\0\7\7\1\133\2\7\3\0\23\7\27\0\4\7"+
    "\2\0\12\7\3\0\1\7\1\134\21\7\27\0\4\7"+
    "\2\0\12\7\3\0\5\7\1\135\15\7\27\0\4\7"+
    "\2\0\12\7\3\0\15\7\1\136\5\7\27\0\4\7"+
    "\2\0\12\7\3\0\4\7\1\137\16\7\23\0\1\113"+
    "\1\0\1\113\1\0\71\113\72\114\1\140\2\114\4\0"+
    "\4\7\2\0\11\7\1\141\3\0\23\7\27\0\4\7"+
    "\2\0\4\7\1\142\5\7\3\0\23\7\27\0\4\7"+
    "\2\0\5\7\1\143\4\7\3\0\23\7\27\0\4\7"+
    "\2\0\5\7\1\144\4\7\3\0\23\7\27\0\4\7"+
    "\2\0\12\7\3\0\5\7\1\145\15\7\27\0\4\7"+
    "\2\0\7\7\1\146\2\7\3\0\23\7\27\0\4\7"+
    "\2\0\10\7\1\147\1\7\3\0\23\7\27\0\4\7"+
    "\2\0\10\7\1\150\1\7\3\0\23\7\27\0\4\7"+
    "\2\0\12\7\3\0\6\7\1\151\14\7\27\0\4\7"+
    "\2\0\5\7\1\152\4\7\3\0\23\7\27\0\4\7"+
    "\2\0\10\7\1\153\1\7\3\0\23\7\27\0\4\7"+
    "\2\0\12\7\3\0\1\154\22\7\27\0\4\7\2\0"+
    "\11\7\1\155\3\0\23\7\27\0\4\7\2\0\11\7"+
    "\1\156\3\0\23\7\27\0\4\7\2\0\10\7\1\157"+
    "\1\7\3\0\23\7\27\0\4\7\2\0\12\7\3\0"+
    "\20\7\1\160\2\7\27\0\4\7\2\0\7\7\1\161"+
    "\2\7\3\0\23\7\23\0\71\114\1\162\1\140\2\114"+
    "\4\0\4\7\2\0\3\7\1\163\6\7\3\0\23\7"+
    "\27\0\4\7\2\0\12\7\3\0\1\7\1\164\21\7"+
    "\27\0\4\7\2\0\12\7\3\0\1\7\1\165\21\7"+
    "\27\0\4\7\2\0\12\7\3\0\16\7\1\166\4\7"+
    "\27\0\4\7\2\0\3\7\1\167\6\7\3\0\23\7"+
    "\27\0\4\7\2\0\5\7\1\170\4\7\3\0\23\7"+
    "\27\0\4\7\2\0\10\7\1\171\1\7\3\0\23\7"+
    "\27\0\4\7\2\0\11\7\1\172\3\0\23\7\27\0"+
    "\4\7\2\0\2\7\1\173\7\7\3\0\23\7\27\0"+
    "\4\7\2\0\5\7\1\174\4\7\3\0\23\7\27\0"+
    "\4\7\2\0\3\7\1\175\6\7\3\0\23\7\27\0"+
    "\4\7\2\0\2\7\1\176\7\7\3\0\23\7\27\0"+
    "\4\7\2\0\12\7\3\0\1\7\1\177\21\7\27\0"+
    "\4\7\2\0\12\7\3\0\6\7\1\200\14\7\27\0"+
    "\4\7\2\0\12\7\3\0\7\7\1\201\13\7\27\0"+
    "\4\7\2\0\6\7\1\202\3\7\3\0\23\7\27\0"+
    "\4\7\2\0\12\7\3\0\13\7\1\203\7\7\27\0"+
    "\4\7\2\0\5\7\1\204\4\7\3\0\23\7\27\0"+
    "\4\7\2\0\7\7\1\205\2\7\3\0\23\7\27\0"+
    "\4\7\2\0\3\7\1\206\6\7\3\0\23\7\27\0"+
    "\4\7\2\0\11\7\1\207\3\0\23\7\27\0\4\7"+
    "\2\0\7\7\1\210\2\7\3\0\23\7\27\0\4\7"+
    "\2\0\5\7\1\211\4\7\3\0\23\7\27\0\4\7"+
    "\2\0\12\7\3\0\1\7\1\212\21\7\27\0\4\7"+
    "\2\0\7\7\1\213\2\7\3\0\23\7\27\0\4\7"+
    "\2\0\12\7\3\0\10\7\1\214\12\7\27\0\4\7"+
    "\2\0\12\7\3\0\1\7\1\215\21\7\27\0\4\7"+
    "\2\0\2\7\1\216\7\7\3\0\23\7\27\0\4\7"+
    "\2\0\12\7\3\0\21\7\1\217\1\7\27\0\4\7"+
    "\2\0\5\7\1\220\4\7\3\0\23\7\27\0\4\7"+
    "\2\0\2\7\1\221\7\7\3\0\23\7\27\0\4\7"+
    "\2\0\5\7\1\222\4\7\3\0\23\7\27\0\4\7"+
    "\2\0\11\7\1\223\3\0\23\7\23\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6344];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\3\1\2\11\20\1\1\11"+
    "\1\1\1\11\1\1\3\11\6\1\1\11\1\1\2\11"+
    "\1\0\6\1\1\0\1\11\1\0\15\1\11\11\1\1"+
    "\1\0\23\1\1\0\21\1\1\11\41\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[147];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */

public String posicion(String token){

       String auxiliar = yytext();
int col = auxiliar.length();
boolean truncado = false;
         if (token.compareTo("Id")==0) {
        if (col>31) {
            auxiliar = auxiliar.substring(0, 31);
truncado = true;
        }
    }
col += yycolumn;
if(truncado){
return "Token: "+ token +" -> " +"<" + auxiliar + "> " +" ***Id truncado*** "+ "Línea: " + yyline + " Columna: " + yycolumn +"-"+col;
}
else{
return "Token: "+ token +" -> " +"<" + auxiliar + "> " + "Línea: " + yyline + " Columna: " + yycolumn +"-"+col;
}
      

}



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  reglas(java.io.Reader in) {
      this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 196) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public String yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
              {
                return "FIN";
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return posicion("Error");
            }
          case 56: break;
          case 2: 
            { 
            }
          case 57: break;
          case 3: 
            { return posicion("Int");
            }
          case 58: break;
          case 4: 
            { return posicion("Id");
            }
          case 59: break;
          case 5: 
            { return posicion(".");
            }
          case 60: break;
          case 6: 
            { return posicion("+");
            }
          case 61: break;
          case 7: 
            { return posicion("(");
            }
          case 62: break;
          case 8: 
            { return posicion(")");
            }
          case 63: break;
          case 9: 
            { return posicion("{");
            }
          case 64: break;
          case 10: 
            { return posicion("}");
            }
          case 65: break;
          case 11: 
            { return posicion("[");
            }
          case 66: break;
          case 12: 
            { return posicion("]");
            }
          case 67: break;
          case 13: 
            { return posicion(",");
            }
          case 68: break;
          case 14: 
            { return posicion(";");
            }
          case 69: break;
          case 15: 
            { return posicion("!");
            }
          case 70: break;
          case 16: 
            { return posicion("=");
            }
          case 71: break;
          case 17: 
            { return posicion(">");
            }
          case 72: break;
          case 18: 
            { return posicion("<");
            }
          case 73: break;
          case 19: 
            { return posicion("%");
            }
          case 74: break;
          case 20: 
            { return posicion("/");
            }
          case 75: break;
          case 21: 
            { return posicion("*");
            }
          case 76: break;
          case 22: 
            { return posicion("-");
            }
          case 77: break;
          case 23: 
            { return posicion("String");
            }
          case 78: break;
          case 24: 
            { return posicion("if");
            }
          case 79: break;
          case 25: 
            { return posicion("()");
            }
          case 80: break;
          case 26: 
            { return posicion("{}");
            }
          case 81: break;
          case 27: 
            { return posicion("[]");
            }
          case 82: break;
          case 28: 
            { return posicion("!=");
            }
          case 83: break;
          case 29: 
            { return posicion("||");
            }
          case 84: break;
          case 30: 
            { return posicion("&&");
            }
          case 85: break;
          case 31: 
            { return posicion("==");
            }
          case 86: break;
          case 32: 
            { return posicion(">=");
            }
          case 87: break;
          case 33: 
            { return posicion("<=");
            }
          case 88: break;
          case 34: 
            { return posicion("comentario");
            }
          case 89: break;
          case 35: 
            { return posicion("for");
            }
          case 90: break;
          case 36: 
            { return posicion("int");
            }
          case 91: break;
          case 37: 
            { return posicion("New");
            }
          case 92: break;
          case 38: 
            { return posicion("this");
            }
          case 93: break;
          case 39: 
            { return posicion("else");
            }
          case 94: break;
          case 40: 
            { return posicion("bool");
            }
          case 95: break;
          case 41: 
            { return posicion("null");
            }
          case 96: break;
          case 42: 
            { return posicion("void");
            }
          case 97: break;
          case 43: 
            { return "comentario";
            }
          case 98: break;
          case 44: 
            { return posicion("break");
            }
          case 99: break;
          case 45: 
            { return posicion("class");
            }
          case 100: break;
          case 46: 
            { return posicion("while");
            }
          case 101: break;
          case 47: 
            { return posicion("Float");
            }
          case 102: break;
          case 48: 
            { return posicion("return");
            }
          case 103: break;
          case 49: 
            { return posicion("string");
            }
          case 104: break;
          case 50: 
            { return posicion("double");
            }
          case 105: break;
          case 51: 
            { return posicion("extends");
            }
          case 106: break;
          case 52: 
            { return posicion("New Array");
            }
          case 107: break;
          case 53: 
            { return posicion("interface");
            }
          case 108: break;
          case 54: 
            { return posicion("Constante");
            }
          case 109: break;
          case 55: 
            { return posicion("implements");
            }
          case 110: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
