
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int guin = 3;
  public static final int slash = 5;
  public static final int EOF = 0;
  public static final int zint = 8;
  public static final int parac = 7;
  public static final int error = 1;
  public static final int aster = 4;
  public static final int mas = 2;
  public static final int para = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "mas",
  "guin",
  "aster",
  "slash",
  "para",
  "parac",
  "zint"
  };
}

