
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int slash = 42;
  public static final int zreadline = 50;
  public static final int admira = 30;
  public static final int aster = 43;
  public static final int llaves = 25;
  public static final int zinterface = 5;
  public static final int zreturn = 12;
  public static final int coma = 28;
  public static final int igual = 36;
  public static final int llc = 21;
  public static final int zclass = 4;
  public static final int lla = 20;
  public static final int parac = 19;
  public static final int coc = 23;
  public static final int coa = 22;
  public static final int zreadinteger = 49;
  public static final int guin = 44;
  public static final int dobleigual = 35;
  public static final int pipes = 31;
  public static final int zFloat = 34;
  public static final int zbreak = 13;
  public static final int zgetbyte = 56;
  public static final int menor = 40;
  public static final int porcentaje = 41;
  public static final int EOF = 0;
  public static final int zsetbyte = 57;
  public static final int pyc = 29;
  public static final int zimplements = 46;
  public static final int mas = 45;
  public static final int andpers = 32;
  public static final int para = 18;
  public static final int error = 1;
  public static final int zif = 10;
  public static final int maigual = 37;
  public static final int mayor = 38;
  public static final int zmalloc = 51;
  public static final int negar = 33;
  public static final int zstring = 3;
  public static final int meigual = 39;
  public static final int zwhile = 9;
  public static final int punto = 27;
  public static final int zNewArray = 15;
  public static final int corcetes = 24;
  public static final int zbool = 55;
  public static final int id = 17;
  public static final int zthis = 7;
  public static final int zconst_string = 52;
  public static final int zconst_int = 58;
  public static final int zint = 54;
  public static final int zprint = 48;
  public static final int znull = 6;
  public static final int zNew = 14;
  public static final int zfor = 47;
  public static final int paren = 26;
  public static final int zextends = 8;
  public static final int zvoid = 2;
  public static final int zdouble = 16;
  public static final int zconstante_double = 53;
  public static final int cbool = 59;
  public static final int zelse = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "zvoid",
  "zstring",
  "zclass",
  "zinterface",
  "znull",
  "zthis",
  "zextends",
  "zwhile",
  "zif",
  "zelse",
  "zreturn",
  "zbreak",
  "zNew",
  "zNewArray",
  "zdouble",
  "id",
  "para",
  "parac",
  "lla",
  "llc",
  "coa",
  "coc",
  "corcetes",
  "llaves",
  "paren",
  "punto",
  "coma",
  "pyc",
  "admira",
  "pipes",
  "andpers",
  "negar",
  "zFloat",
  "dobleigual",
  "igual",
  "maigual",
  "mayor",
  "meigual",
  "menor",
  "porcentaje",
  "slash",
  "aster",
  "guin",
  "mas",
  "zimplements",
  "zfor",
  "zprint",
  "zreadinteger",
  "zreadline",
  "zmalloc",
  "zconst_string",
  "zconstante_double",
  "zint",
  "zbool",
  "zgetbyte",
  "zsetbyte",
  "zconst_int",
  "cbool"
  };
}

